# Site Settings
title: "Ioannis Psomadakis"
description: "Experienced Data Scientist and Machine Learning Specialist"
url: "https://ioannis-psomadakis.github.io"
baseurl: ""  # The subpath of your site, e.g. "/blog"

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"  # Adjust according to your theme
minimal_mistakes_skin: "dark"  # Skin choice (dark, air, aqua, etc.)

# Social Links
social:
  name: "Ioannis Psomadakis"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:psomadakis.ioannis@hotmail.com"
    - label: "LinkedIn"
      icon: "fas fa-linkedin-in"
      url: "https://www.linkedin.com/in/ioannis-psomadakis-1092aa24b/"

# Site Author
author:
  name: "Ioannis Psomadakis"
  avatar: "/assets/images/profile.jpg"
  bio: "Dynamic Data Scientist specializing in data analysis, machine learning, visualization, and statistical modeling."
  location: "Amsterdam, Netherlands"

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Markdown Processing
markdown: kramdown
highlighter: rouge

# Exclusions
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - node_modules
  - package.json
  - README

# Archive Pages
category_archive:
  type: liquid
  path: "/categories/"

tag_archive:
  type: liquid
  path: "/tags/"

# Google Analytics (optional)
analytics:
  provider: "google"
  google:
    tracking_id: "UA-XXXXXXX-X"